### ISSUE TITLE
Output lists of gene definition

### ISSUE THREAD

**Issue by lisemangiante** [reimandlab/ActivePathways#11]
Hi again!
Thank you for your effort in this repository, it is well documented!! However, I may have a question about how I should extract the genes from the res R object (from res <- ActivePathways(scores, gmt.file, cytoscape.file.tag = "enrichmentMap__") ) for a given enriched pathway. I understand that they are listed in the Genes_X3UTR in the case where this pathway is enriched because of the X3UTR dataset but what about the "overlap" column? What is your definition of this list of genes?

Very sorry if you've already answered this question and I missed it,
Many thanks in advance for your assistance,
Best,
Lise

**Comment by reimand0** [comment]
Hi Lise,

The overlap column contains the genes of the pathway that are enriched in
your multi-omics dataset after the data fusion (p-value merging) step.
Arguably this is the main gene list you should focus on. As a schematic,

(dataset1, dataset2, .., datasetM) > [data fusion] > (ranked gene list) >
> [pathway enrichment using ranked hypergeometric] > (pathway1, pathway2,
.. pathwayN) >
> [extract genes common to pathwayX and ranked gene list] >  (overlap1,
overlap2, .. overlapN)

I will add a short summary about it in the tutorial.

thanks for pointing out the limited documentation.

best,
Jüri

**Comment by reimand0** [comment]
will close this now, please feel free to get in touch again if you have questions.
