### ISSUE TITLE
How to create the tsv of p value?

### ISSUE THREAD

**Issue by ggoodstudydaydayup** [reimandlab/ActivePathways#12]
Hi,
    I want to use this package to analyze my snp data. But I have a problem to create the tsv of p value. 
    Could you give me some advice?
    Thanks in advance.
Best wishes !
Liu

**Comment by reimand0** [comment]
Hi Liu,

SNP data analysis comes with additional challenges that are not solved by
this package (many SNPs are not in genes; one gene may have multiple SNPs).
You need to solve these challenges first by assigning SNP p-values to
genes. Then make each input dataset into this format:

gene_symbol pvalue
GENE1 0.001
GENE2 0.3
GENE3 0.000006

Then in R, when you have two data.frames like that (dfr1, dfr2), you should
look at the R command merge(). Specifically, all=TRUE will merge such that
missing genes in one dataset will receive NA p-values in the other dataset.

combined_dfr = merge(dfr1, dfr2, by = "gene_symbol", all = TRUE)

I hope this helps. All the best,

Jüri
