### ISSUE TITLE
TCGA analysis

### ISSUE THREAD

**Issue by DrZhaoJie** [reimandlab/ActivePathways#15]
Hi, this package and article was based on the analysis on PCAWG datasets. May I apply it to WES datasets ftom TCGA open access data? Thank you very much!

**Comment by reimand0** [comment]
Hi Watson - yes you can certainly apply this method to TCGA WES data. You
would need to figure out how to compute p-values for genes, for example
using WES-based driver gene discovery methods.
best,
Jüri
