### ISSUE TITLE
Package archived from CRAN

### ISSUE THREAD

**Issue by keremw** [reimandlab/ActivePathways#16]
Hi,
Thank you for your package. I use it a lot. I've noticed it was archived from CRAN. Is there a relevant reason for the archive? 
Thank you for all the hard work.
Kerem

**Comment by reimand0** [comment]
Hi Kerem, 
thanks for the positive feedback! One of our package's dependencies in the testing functions was archived and this cascaded to our package due to CRAN regulations. We are working on a fix, please stay tuned. 
best,
Jüri
