### ISSUE TITLE
incomplete color legend with custom colors

### ISSUE THREAD

**Issue by reimand0** [reimandlab/ActivePathways#17]
When using a custom color palette for Cytoscape output, the color for the combined-only results does not show a label in the generated PDF. However, when not using a custom color palette, the label is shown as expected ("combined"). 

A minor note, "combined" could be replaced with something more informative and visible, such as "INTEGRATED-ONLY".

**Comment by MSlobody** [comment]
Thank you. This has been addressed as part of the ActivePathways version 1.1.1 update.
