### ISSUE TITLE
Error when additional arguments are not recognized

### ISSUE THREAD

**Issue by keremw** [reimandlab/ActivePathways#23]
The latest update caused the function to not recognize the additional arguments. I've been using ActivePathways since it came out. and now when I try to run my code I get:

> Error in ActivePathways(scores = as.matrix(pvals_table), gmt = gmt.file,  : 
>   unused arguments (geneset.filter = c(10, 500), cytoscape.file.tag = "Name")

Would be happy for your support.
Thank you for this great tool.
Kerem

**Comment by reimand0** [comment]
Hi Kerem,

Thanks for the feedback and sorry for the trouble. Try replacing the
parameter names such that points become underscores, for example
geneset.filter to geneset_filter.

We have a Python package under development and points in arguments do not
work, so we updated these parameter names in V2.0 onwards to keep things
consistent.

best,
Jüri

**Comment by keremw** [comment]
Thank you for the quick answer.
It did indeed fix the problem. I didn't even notice the difference in the arguments names although I was reading the help section. Sometimes the human eye is deceiving us...  
Best wishes,
Kerem
