### ISSUE TITLE
 miRNA results

### ISSUE THREAD

**Issue by owehann** [reimandlab/ActivePathways#24]
Hi, I want to know if the differential miRNA results are applicable to DPM.

**Comment by reimand0** [comment]
Hi Owehann,

Thanks for your message. Directional integration should work for miRNAs too
and it sounds like an interesting project. You should be able to prioritise
individual miRNAs based on significance and fold-change directions,
depending on how your datasets are set up.

However, pathway analysis is limited to gene functional annotations that
are mostly available for protein-coding genes. Linking miR activity to
protein-coding genes would be beneficial, or perhaps looking for miR target
gene information as GMT files.

I hope this helps. Happy to discuss further offline.

Jüri
