### ISSUE TITLE
rows were removed from scores because they are not found in the background

### ISSUE THREAD

**Issue by suderiss** [reimandlab/ActivePathways#25]
Hi,

I am using the ActivePathways tool, but I am encountering an issue

`2861 rows were removed from scores because they are not found in the background
`
I believe there might be an underlying problem here, but I haven't been able to figure it out.

Here is my scores matrix:

              

>   ATAC-Seq           RNA-Seq 
> A0A024R962  1.000000000                0 
> P08603           1.000000000                0
> A0A0D9SG88 1.000000000               0 
> C9JPG5     0.001133218       1
> Q59G50     0.001133218       1
> Q13275     0.001133218       1

My matrix has Uniprot ID but I also tried with entrez ID and HGNC symbols. But the result is the same. I could not understand the problem but the number of the rows seemed a bit odd to me.

**Comment by reimand0** [comment]
The IDs in your scores matrix need to match the IDs in the GMT file (ie. the gene sets representing pathways,processes, etc). The background in composed of the GMT file content by default, but you can set it to a custom gene set as well. I hope this helps!
