### ISSUE TITLE
Issue with ActivePathways

### ISSUE THREAD

**Issue by prajishiyer** [reimandlab/ActivePathways#3]
Hi 
I m not a bioinformatics person. I just followed what was written in the github. and I got this error. If there is a code for running the ActivePathways. Can you please share? piyer@coh.org

I ran this code
> dat <- as.matrix(read.table('C:/Users/praji/Documents/NSG vs Primary.txt.txt',fill= TRUE, header=TRUE, row.names= 1))
> dat[is.na(dat)] <- 1
> activePathways(dat, 'C:/Users/praji/Documents/NSGPrimary.gmt', return.all=TRUE,
+                cytoscape.file.dir="results")
Error in activePathways(dat, "C:/Users/praji/Documents/NSGPrimary.gmt",  : 
  All values in scores must be in [0,1]

**Comment by reimand0** [comment]
Hello - thank you for getting in touch. Can you please share some of your data in the files "NSG vs Primary.txt.txt" and "NSGPrimary.gmt". ActivePathways assumes as input a set of p-values (such as those from limma or EdgeR in RNA-seq analysis). Based on the error message, you may have inserted other kinds of values in the file "NSG vs Primary.txt.txt". best wishes, Jüri


On Wed, Feb 19, 2020 at 9:58 PM prajishiyer <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi
I m not a bioinformatics person. I just followed what was written in the github. and I got this error. If there is a code for running the ActivePathways. Can you please share? piyer@coh.org<mailto:piyer@coh.org>

I ran this code

dat <- as.matrix(read.table('C:/Users/praji/Documents/NSG vs Primary.txt.txt',fill= TRUE, header=TRUE, row.names= 1))
dat[is.na<http://is.na>(dat)] <- 1
activePathways(dat, 'C:/Users/praji/Documents/NSGPrimary.gmt', return.all=TRUE,

  *

           cytoscape.file.dir="results")


Error in activePathways(dat, "C:/Users/praji/Documents/NSGPrimary.gmt", :
All values in scores must be in [0,1]

**Comment by reimand0** [comment]
closing this issue as the problem was related to invalid input to ActivePathways. The primary input is a matrix of p-values expected to include values in the range [0..1].
