### ISSUE TITLE
ActivePathways results visualization

### ISSUE THREAD

**Issue by lisemangiante** [reimandlab/ActivePathways#4]
Hi, 
First, thank you for your work on this very useful tool! I did not have any issue to run your function. 
However, I don't really get how you obtained the Nat Commun paper figures with the nodes represented with pie charts showing the contribution of each dataset in the enrichment results. I used Cytoscape EnrichmenMap and load my ActivePathways output folder (with legend.pdf, pathways.txt, pathways.gmt and subgroups.txt files) and I can see the network in the EnrichmenMap view but I can't find the way to get the pie chart in the node with the contribution of each dataset I used. By default, it assumes that my first dataset is "pathways" and my second one is "subgroups". How can I change that?

Many thanks in advance for your help!
Best,
Lise

**Comment by reimand0** [comment]
Hi Lise,

thanks for getting in touch. The visualization requires a few steps in Cytoscape as described below. Please let me know if it makes sense to you. We will extend the online documentation - your feedback is very helpful.

1. Install EhancedGraphics app of Cytoscape, see menu Apps>App manager… or http://apps.cytoscape.org/apps/enhancedGraphics

2. import your subgroups.txt table into Cytoscape using File > Import > Table from File ..

3. Navigate to Style panel and add new visual property called Image/Chart 1. This appears under Control Panel: Properties > Paint > Custom Paint.

4. The new visual property Image/Chart 1 appears, select Column to be instruct and Mapping type to be Passthrough Mapping.

5. Colors in the enrichment map get updated. Now each node is colored according to omics evidence that provided that enrichment. The file legend.pdf should now correspond to the colors in the enrichment map.

If this doesn't work, you could also send your files to juri-dot-reimand-at-utoronto-dot-ca and I can have a look.

best,
Jüri

On Tue, Mar 10, 2020 at 12:02 PM lisemangiante <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi,
First, thank you for your work on this very useful tool! I did not have any issue to run your function.
However, I don't really get how you obtained the Nat Commun paper figures with the nodes represented with pie charts showing the contribution of each dataset in the enrichment results. I used Cytoscape EnrichmenMap and load my ActivePathways output folder (with legend.pdf, pathways.txt, pathways.gmt and subgroups.txt files) and I can see the network in the EnrichmenMap view but I can't find the way to get the pie chart in the node with the contribution of each dataset I used. By default, it assumes that my first dataset is "pathways" and my second one is "subgroups". How can I change that?

Many thanks in advance for your help!
Best,
Lise

**Comment by reimand0** [comment]
Hi Lise,

in R, type
browseVignettes(package='ActivePathways')

This should open the following URL in your browser:
http://127.0.0.1:11212/library/ActivePathways/doc/enrichmentMap-vignette.html

This documents the above procedure with some screenshots. Note that your Cytoscape may look a little different as it is frequently updated.

best,
Jüri



On Wed, Mar 11, 2020 at 9:25 PM Jüri Reimand <juri.reimand@utoronto.ca<mailto:juri.reimand@utoronto.ca>> wrote:
Hi Lise,

thanks for getting in touch. The visualization requires a few steps in Cytoscape as described below. Please let me know if it makes sense to you. We will extend the online documentation - your feedback is very helpful.

1. Install EhancedGraphics app of Cytoscape, see menu Apps>App manager… or http://apps.cytoscape.org/apps/enhancedGraphics

2. import your subgroups.txt table into Cytoscape using File > Import > Table from File ..

3. Navigate to Style panel and add new visual property called Image/Chart 1. This appears under Control Panel: Properties > Paint > Custom Paint.

4. The new visual property Image/Chart 1 appears, select Column to be instruct and Mapping type to be Passthrough Mapping.

5. Colors in the enrichment map get updated. Now each node is colored according to omics evidence that provided that enrichment. The file legend.pdf should now correspond to the colors in the enrichment map.

If this doesn't work, you could also send your files to juri-dot-reimand-at-utoronto-dot-ca and I can have a look.

best,
Jüri

On Tue, Mar 10, 2020 at 12:02 PM lisemangiante <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi,
First, thank you for your work on this very useful tool! I did not have any issue to run your function.
However, I don't really get how you obtained the Nat Commun paper figures with the nodes represented with pie charts showing the contribution of each dataset in the enrichment results. I used Cytoscape EnrichmenMap and load my ActivePathways output folder (with legend.pdf, pathways.txt, pathways.gmt and subgroups.txt files) and I can see the network in the EnrichmenMap view but I can't find the way to get the pie chart in the node with the contribution of each dataset I used. By default, it assumes that my first dataset is "pathways" and my second one is "subgroups". How can I change that?

Many thanks in advance for your help!
Best,
Lise
